name: android_device_id_generator
description: A package to generate fake Android device IDs, in the same format as Android's Settings.Secure.ANDROID_ID.
version: 0.1.0
homepage: https://github.com/hacker1024/android_device_id_generator.dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  lint: ^1.5.3
  test: ^1.16.8
